### PR TITLE
Used better code for Attributes 

### PR DESCRIPTION
**Pull request by Brandonbr1**

### CODE REVIEW

**Review by KingOfTheGamesYT — COMMENTED** [review]
there's no need to make a whole other class to register the attributes when you can do it in the main class. Also no need for additional info on the owner of DangerZone (Game)

**Comment by Brandonbr1** [comment]
the changes requested were done but they don't seem to come up on gh

**Comment by KingOfTheGamesYT** [comment]
try now

**Review by Brandonbr1 — COMMENTED** [review]
unable to delete DeferredWorkQueue.runLater contents in gh it will give a conflict either Dev master you need delete the contents in DeferredWorkQueue.runLater   or you merge the other pr that you closed and change the contents in DeferredWorkQueue.runLater to event.enqueueWork

or you could
screw this GitHub pr merge the other pr at #14 it will make both of our lives easier pls do that one!

-Brandonbr1

**Pull request closed without merging**
